[package]
name = "session-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buffer = { path = "../../buffer" }
net = { path = "../../net" }
protocol-common = { path = "../../protocol/common" }
rustcommon-time = { git = "https://github.com/twitter/rustcommon" }