[package]
name = "server"
version = "0.1.0"
edition = "2021"
authors = ["Brian Martin <bmartin@twitter.com>"]
description = "core server event loops and threads for Pelikan servers"
homepage = "https://pelikan.io"
repository = "https://github.com/twitter/pelikan"
license = "Apache-2.0"

[dependencies]
admin = { path = "../admin" }
common = { path = "../../common" }
config = { path = "../../config" }
crossbeam-channel = "0.5.0"
entrystore = { path = "../../entrystore" }
logger = { path = "../../logger" }
net = { path = "../../net" }
protocol-admin = { path = "../../protocol/admin" }
protocol-common = { path = "../../protocol/common" }
queues = { path = "../../queues" }
rustcommon-metrics = { git = "https://github.com/twitter/rustcommon" }
session-common = { path = "../../session/common" }
slab = "0.4.2"
waker = { path = "../waker" }