[package]
name = "protocol-resp"
authors = ["Brian Martin <bmartin@twitter.com>"]

version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
common = { path = "../../common" }
nom = { workspace = true }
protocol-common = { path = "../../protocol/common" }
rustcommon-metrics = { workspace = true }
