[package]
name = "protocol-resp"
version = "0.2.0"
edition = "2021"
authors = ["Brian Martin <bmartin@twitter.com>"]
homepage = "https://pelikan.io"
repository = "https://github.com/twitter/pelikan"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
nom = "5.1.2"
protocol-common = { path = "../../protocol/common" }
rustcommon-metrics = { git = "https://github.com/twitter/rustcommon" }
