sudo: false
language: c
dist: xenial

# using anchor to import sources into linux builds
addons:
  apt: &apt
    sources:
      - ubuntu-toolchain-r-test

# important for allowed-to-fail matching
# see https://docs.travis-ci.com/user/customizing-the-build#Rows-that-are-Allowed-to-Fail
env:
  - ALLOWED_TO_FAIL=0

# travis currently does not support directly setting gcc/clang with versions
# (e.g. gcc-4.8) as value for the compiler key. So we will have to manually
# request these packages and use environment varibles to create the matrix.
matrix:
  include:
    - name: "gcc-5 on Linux"
      compiler: gcc
      addons:
        apt:
          <<: *apt
          packages:
            - libsubunit-dev

    - name: "gcc-5 on Linux, Rust enabled"
      compiler: gcc
      env:
        - RUST_ENABLED=1
      addons:
        apt:
          <<: *apt
          packages:
            - libsubunit-dev

    - os: osx
      osx_image: xcode10.1
      compiler: clang

    - name: "cargo build"
      language: rust
      addons:
        apt:
          <<: *apt
          packages:
            - libsubunit-dev
      script:
        - ./ci/cargo.sh

    - os: osx
      osx_image: xcode10.1
      language: rust
      script:
        - ./ci/cargo.sh

  allow_failures:
    - os: osx
      osx_image: xcode10.1
      compiler: clang
    - os: osx
      osx_image: xcode10.1
      language: rust
      script:
        - ./ci/cargo.sh

before_install:
  - ./ci/before-install.sh

script:
  - ./ci/run.sh
