name: 'Configure and run pingproxy'
description: 'Configures and runs the pingproxy'
inputs:
  tls:
    description: 'Enable TLS'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Configure
      run: |
        echo "[admin]" >> proxy.toml
        echo "port = \"9998\"" >> proxy.toml
        echo "[backend]" >> proxy.toml
        echo "endpoints = [\"127.0.0.1:12321\"]" >> proxy.toml
      shell: bash
    - name: Configure TLS
      run: |
          if ${{ inputs.tls }}; then
          step ca certificate --san=127.0.0.1 --ca-url=127.0.0.1:443 --provisioner-password-file=${HOME}/.step/password localhost proxy.crt proxy.key
          echo "[tls]" >> proxy.toml
          echo "certificate_chain = \"root.crt\"" >> proxy.toml
          echo "certificate = \"proxy.crt\"" >> proxy.toml
          echo "private_key = \"proxy.key\"" >> proxy.toml
          fi
      shell: bash
    - name: Build pingproxy
      run: |
        cd pelikan && cargo build --release --bin pelikan_pingproxy_rs
      shell: bash
    - name: Run pingproxy
      run: |
        ./pelikan/target/release/pelikan_pingproxy_rs proxy.toml &
        sleep 10
      shell: bash
