[package]
name = "protocol-http"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.2"
bytes = "1.2.1"
bstr = "1.0.1"
httparse = "1.8.0"
thiserror = "1.0.37"
urlencoding = "2.1.2"

phf = { version = "0.11.1", features = ["macros"] }

protocol-common = { path = "../common" }
logger = { path="../../logger" }
