[package]
name = "datapool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "*"
libc = "*"
memmap2 = "*"
rustcommon-time = { git = "https://github.com/twitter/rustcommon" }

[dev-dependencies]
tempfile = "*"