[package]
name = "datapool"
version = "0.1.0"
edition = "2021"
authors = ["Brian Martin <bmartin@twitter.com>"]
description = "abstractions for byte storage pools"
homepage = "https://pelikan.io"
repository = "https://github.com/twitter/pelikan"
license = "Apache-2.0"

[dependencies]
blake3 = "1.3.1"
common = { path = "../../common" }
libc = "0.2.125"
memmap2 = "0.5.3"

[dev-dependencies]
tempfile = "3.3.0"
