[package]
name = "queues"
version = "0.2.0"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
description = "queue types for inter-process communication"
homepage = "https://pelikan.io"
repository = "https://github.com/twitter/pelikan"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.2"
mio = { version = "0.7.7", features = ["os-poll", "tcp"] }
rand = "0.8.5"
rand_chacha = "0.3.1"