[package]
name = "httpencode"
version = "0.1.0"
authors = ["Sean Lynch <slynch@twitter.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[features]
std = [ "bytes/std", "arrayvec/std", "httpdate" ]
default = [ "std" ]

[dependencies]
bytes = { version="0.5.1", default-features = false }
memchr = "2.2.1"

[dependencies.arrayvec]
version="0.5.1"
default-features=false
features = [ "array-sizes-33-128" ]

[dependencies.httpdate]
version = "0.3.2"
optional = true

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "compose"
harness = false
