[package]
name = "service-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol-common = { path = "../../protocol/common" }
rustcommon-metrics = { git = "https://github.com/twitter/rustcommon" }
session = { path = "../../session" }
