[package]
name = "cdb_utils"
version = "0.1.0"
authors = ["Jonathan D. Simms <jsimms@twitter.com>"]

[dependencies]
cdb_rs = { path = "../cdb_rs" }
clap = "~2.31.0"
log = "~0.4"
env_logger = "~0.5.10"
rand = "~0.5"
bytes = "~0.4"
