[package]
name = "logger"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../config" }
log = { version = "0.4.8", features = ["std", "release_max_level_debug"] }
mpmc = "*"
rustcommon-time = { git = "https://github.com/twitter/rustcommon" }