[package]
name = "protocol-admin"
version = "0.0.1"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
description = "Admin ASCII protocol used in Pelikan servers"
homepage = "https://pelikan.io"
repository = "https://github.com/twitter/pelikan"
license = "Apache-2.0"

[dependencies]
common = { path = "../../common" }
config = { path = "../../config" }
logger = { path = "../../logger" }
protocol-common = { path = "../../protocol/common" }
session-legacy = { path = "../../session/legacy" }
storage-types = { path = "../../storage/types" }

[dev-dependencies]
criterion = "0.3.4"
