[package]
name = "pingproxy"
version = "0.0.1"
edition = "2021"
authors = ["Brian Martin <bmartin@twitter.com>"]
homepage = "https://pelikan.io"
repository = "https://github.com/twitter/pelikan"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pingproxy"
path = "src/lib.rs"
doc = true

[[bin]]
name = "pelikan_pingproxy_rs"
path = "src/main.rs"
doc = false

[dependencies]
backtrace = "0.3.56"
clap = "2.33.3"
common = { path = "../../common" }
config = { path = "../../config" }
logger = { path = "../../logger" }
proxy = { path = "../../core/proxy" }
protocol-ping = { path = "../../protocol/ping", features = ["client", "server"] }