name: 'Configure and run pingserver'
description: 'Configures and runs the pingserver'
env:
  BASE_CONFIG: |
    [admin]
    port = "9999"
  TLS_CONFIG: |
    [tls]
    certificate_chain = "root.crt"
    certificate = "server.crt"
    private_key = "server.key"
inputs:
  tls:
    description: 'Enable TLS'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Configure
      run: echo "$BASE_CONFIG" >> server.toml
      env:
        BASE_CONFIG: |
        [admin]
        port = "9999"
      shell: bash
    - name: Generate TLS Key/Cert
      run: |
        if ${{ inputs.tls }}; then
          step ca certificate --san=127.0.0.1 --ca-url=127.0.0.1:443 --provisioner-password-file=${HOME}/.step/password localhost server.crt server.key
        fi
      shell: bash
    - name: Configure TLS
      run: if ${{ inputs.tls }}; then echo "$TLS_CONFIG" >> server.toml; fi
      env:
        TLS_CONFIG: |
          [tls]
          certificate_chain = "root.crt"
          certificate = "server.crt"
          private_key = "server.key"
      shell: bash
    - name: Build pingserver
      run: |
        cd pelikan && cargo build --release --bin pelikan_pingserver_rs
      shell: bash
    - name: Run pingserver
      run: |
        ./pelikan/target/release/pelikan_pingserver_rs server.toml &
        sleep 10
      shell: bash
