name: cargo-build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-12 ]
        profile: [ release, debug ]
    name: build-${{ matrix.os }}-${{ matrix.profile }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Update cargo flags
        if: ${{ matrix.profile == 'release' }}
        run: echo 'CARGO_FLAGS=--release' >> $GITHUB_ENV
        shell: bash
      - name: Update cargo flags
        if: ${{ matrix.profile == 'debug' }}
        run: echo 'CARGO_FLAGS=' >> $GITHUB_ENV
        shell: bash

      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.profile }}
      - uses: actions-rs/cargo@v1
        name: build
        with:
          command: test
          args: ${{ env.CARGO_FLAGS }} --workspace --all-features --tests --lib --bins --examples --no-run
      - uses: actions-rs/cargo@v1
        name: test
        with:
          command: test
          args: ${{ env.CARGO_FLAGS }} --workspace  --all-features --tests --lib --bins --examples
      - uses: actions-rs/cargo@v1
        if: ${{ matrix.profile == 'debug' }}
        name: doctests
        with:
          command: test
          args: ${{ env.CARGO_FLAGS }} --workspace --all-features --doc -- --test-threads 16

  bench-check:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-12 ]
    name: build-${{ matrix.os }}-bench
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Update cargo flags
        if: ${{ matrix.profile == 'release' }}
        run: echo 'CARGO_FLAGS=--release' >> $GITHUB_ENV
        shell: bash
      - name: Update cargo flags
        if: ${{ matrix.profile == 'debug' }}
        run: echo 'CARGO_FLAGS=' >> $GITHUB_ENV
        shell: bash

      - uses: Swatinem/rust-cache@v1
        with:
          key: bench
      - uses: actions-rs/cargo@v1
        name: build
        with:
          command: bench
          args: --workspace --no-run

  # Fast cargo check to ensure things compile
  check:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-12 ]
    name: check-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  # Note: We could run these using the pull_request_target trigger. I haven't
  #       done this since I'm not sure if it would be secure.
  #
  # See this link for more details on this
  # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
        with:
          key: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo audit
        run: |
          cargo install cargo-audit
          cargo audit

  smoketest-pingserver:
    name: smoketest-pingserver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: pelikan
      - name: Build Cache for Pelikan
        uses: Swatinem/rust-cache@v1
        with:
          key: pelikan
          working-directory: pelikan
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: ./pelikan/.github/actions/ca
      - uses: ./pelikan/.github/actions/pingserver
        with:
          tls: false
      - uses: ./pelikan/.github/actions/rpc-perf
        with:
          protocol: ping
          port: 12321
          tls: false

  smoketest-pingserver-tls:
    name: smoketest-pingserver-tls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: pelikan
      - name: Build Cache for Pelikan
        uses: Swatinem/rust-cache@v1
        with:
          key: pelikan
          working-directory: pelikan
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: ./pelikan/.github/actions/ca
      - uses: ./pelikan/.github/actions/pingserver
        with:
          tls: true
      - uses: ./pelikan/.github/actions/rpc-perf
        with:
          protocol: ping
          port: 12321
          tls: true

  smoketest-pingproxy:
    name: smoketest-pingproxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: pelikan
      - name: Build Cache for Pelikan
        uses: Swatinem/rust-cache@v1
        with:
          key: pelikan
          working-directory: pelikan
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: ./pelikan/.github/actions/ca
      - uses: ./pelikan/.github/actions/pingserver
        with:
          tls: false
      - uses: ./pelikan/.github/actions/pingproxy
        with:
          tls: false
      - uses: ./pelikan/.github/actions/rpc-perf
        with:
          protocol: ping
          port: 12322
          tls: false

  smoketest-pingproxy-tls-terminating:
    name: smoketest-pingproxy-tls-terminating
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: pelikan
      - name: Build Cache for Pelikan
        uses: Swatinem/rust-cache@v1
        with:
          key: pelikan
          working-directory: pelikan
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: ./pelikan/.github/actions/ca
      - uses: ./pelikan/.github/actions/pingserver
        with:
          tls: false
      - uses: ./pelikan/.github/actions/pingproxy
        with:
          tls: true
      - uses: ./pelikan/.github/actions/rpc-perf
        with:
          protocol: ping
          port: 12322
          tls: true

  smoketest-exposition:
    name: smoketest-exposition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: pelikan
      - name: Build Cache for Pelikan
        uses: Swatinem/rust-cache@v1
        with:
          key: pelikan
          working-directory: pelikan
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: ./pelikan/.github/actions/pingserver
        with:
          tls: false   
      - name: Validate
        run: sleep 60 && curl -s http://localhost:9998/vars.json | jq '.' > /dev/null
