name: cmake-build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-18.04, macos-10.15 ]
        profile: [ Release ]
    name: build-${{ matrix.os }}-${{ matrix.profile }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: |
          mkdir -p _build
          cmake -B _build -S legacy \
            -DCMAKE_BUILD_TYPE=${{ matrix.profile }} \
            -DBUILD_AND_INSTALL_CHECK=yes

      - name: Build
        run: |
          cmake --build _build

      - name: Test
        run: |
          cmake --build _build --target test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1

      - name: Integration tests
        run: |
          cd test/integration
          python test_twemcache.py