on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-18.04, macos-10.15 ]
        profile: [ Release, Debug ]
    name: build-${{ matrix.os }}-${{ matrix.profile }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: ccache-${{ matrix.os }}-${{ matrix.profile }}
      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.os }}-${{ matrix.profile }}

      - name: Configure
        run: |
          mkdir -p _build
          cmake -B _build -S . \
            -DCMAKE_BUILD_TYPE=${{ matrix.profile }} \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DBUILD_AND_INSTALL_CHECK=yes

      - name: Build
        run: |
          cmake --build _build

      - name: Test
        run: |
          ctest _build --output-on-failure

      - name: Integration tests
        run: |
          cd test/integration
          python test_twemcache.py